name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  deploy:

    runs-on: ubuntu-latest


    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGE_TOKEN }}

    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build --no-cache && docker-compose push

    - name: Scan image
      uses: anchore/scan-action@v3
      with:
        image: "ghcr.io/brandoncamenisch/release-the-code-litecoin/litecoin:0.18.1"
        fail-build: true
        severity-cutoff: critical


